### ISSUE TITLE
Fetch data and watch data

### ISSUE THREAD

**Issue by NataPeralta** [HubSpot/hubspot-cms-vscode#204]
Use the new UI interface to be able to synchronize information and listen to files.

Just as now there is the selection of accounts and adding new accounts, with this suggestion you can stop doing commands and make it easier to fetch and watch files

Speed up processes and it would be visually more comfortable and practical to use

**Comment by jsines** [comment]
Hi there! 👋 

Glad to hear some excitement around our new extension features, we really appreciate community feedback! Remote file interactions are currently in the development pipeline and actively being worked on for an upcoming release. Since this is feature is already present in our internal issue tracker I'm going to close this as a duplicate, but rest assured it's on its way soon!
